### ISSUE TITLE
how can i execute this program in my local eclipse

### ISSUE THREAD

**Issue by ghost** [Krzyjan/xls-to-csv#1]
Could you tell me how can I execute this program in my eclipse..I am using maven as build tool._

**Comment by Krzyjan** [comment]
Something like this could be Run as a Scala app:
`
package org.krzyjan.utilities

import java.io.FileInputStream

object SampleMain {
    def main(args: Array[String]) = {
         args.foreach { x => 
            POIXLStoCSV.convert(new FileInputStream(x)).foreach { row => System.out.println(row.mkString(",")) } 
         }
   }
}
`
